version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:latest
    container_name: wastewise-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: management_deseuri
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - wastewise-network
    restart: unless-stopped

  # Backend API (NestJS)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: wastewise-backend
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    networks:
      - wastewise-network
    restart: unless-stopped

  # Frontend (React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: wastewise-frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    networks:
      - wastewise-network
    restart: unless-stopped
    depends_on:
      - backend

  # ML Service (Python/FastAPI)
  ml-service:
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    container_name: wastewise-ml-service
    ports:
      - "8000:8000"
    volumes:
      - ./ml-service:/app
    env_file:
      - ./ml-service/.env
    networks:
      - wastewise-network
    restart: unless-stopped
    depends_on:
      - postgres

networks:
  wastewise-network:
    driver: bridge

volumes:
  pgdata:
