# Dockerfile pentru mediul de dezvoltare
FROM node:22-alpine

# Setăm directorul de lucru
WORKDIR /app

# Instalăm dependențele globale necesare și curățăm cache-ul
RUN npm install -g @nestjs/cli && \
    npm cache clean --force && \
    rm -rf /tmp/* /var/cache/apk/*

# Copiem package.json și package-lock.json
COPY package*.json ./

# Instalăm dependențele
RUN npm ci && \
    npm cache clean --force

# Copiem restul codului sursă
COPY . .

# Expunem porturile pentru aplicație și debugging
EXPOSE 3000 9229

# Comanda pentru rularea aplicației în modul de dezvoltare
CMD ["npm", "run", "start:dev"]
