#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Executare linting pentru backend
echo "🔍 Verificare linting pentru backend..."
cd backend && npm run lint

# Executare linting pentru frontend
echo "🔍 Verificare linting pentru frontend..."
cd ../frontend && npm run lint
